//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticPharmacyInformationSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacySystemEntities : DbContext
    {
        private static PharmacySystemEntities _context;

        public static PharmacySystemEntities GetContext()
        {
            if (_context == null)
                _context = new PharmacySystemEntities();
            return _context;
        }
        public PharmacySystemEntities()
            : base("name=PharmacySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<indent> indent { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<preparation> preparation { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<status_indent> status_indent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
